// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtZzauKFkaL29LYDk-LIgpu5roXjI6bL0',
    appId: '1:575765203466:web:5cd075a7af2fcd5f9a2df3',
    messagingSenderId: '575765203466',
    projectId: 'fyp1-95216',
    authDomain: 'fyp1-95216.firebaseapp.com',
    storageBucket: 'fyp1-95216.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmL2RiGXG8Nv8Lpkr2AOixM5mKy_KMktk',
    appId: '1:575765203466:android:933dfba73ec719b39a2df3',
    messagingSenderId: '575765203466',
    projectId: 'fyp1-95216',
    storageBucket: 'fyp1-95216.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7SqQhuTArYw_6ckFgo8tvzbdmgXa6Rq0',
    appId: '1:575765203466:ios:0baf7d64c769eb629a2df3',
    messagingSenderId: '575765203466',
    projectId: 'fyp1-95216',
    storageBucket: 'fyp1-95216.firebasestorage.app',
    iosBundleId: 'com.example.carbonQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7SqQhuTArYw_6ckFgo8tvzbdmgXa6Rq0',
    appId: '1:575765203466:ios:0baf7d64c769eb629a2df3',
    messagingSenderId: '575765203466',
    projectId: 'fyp1-95216',
    storageBucket: 'fyp1-95216.firebasestorage.app',
    iosBundleId: 'com.example.carbonQuizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtZzauKFkaL29LYDk-LIgpu5roXjI6bL0',
    appId: '1:575765203466:web:a536915bc7e392509a2df3',
    messagingSenderId: '575765203466',
    projectId: 'fyp1-95216',
    authDomain: 'fyp1-95216.firebaseapp.com',
    storageBucket: 'fyp1-95216.firebasestorage.app',
  );
}
